### ISSUE TITLE
Out of Memory exception on large pieces of HTML

### ISSUE THREAD

**Issue by mattiasgeniar** [spatie/robots-txt#19]
An interesting thing happens when you read very large contents of HTML and apply the `findRobotsMetaTagLine($html)` method: it runs out of memory.

```
Allowed memory size of 268435456 bytes exhausted
```

The problem occurs here:

```php
$lines = explode(PHP_EOL, $html);
```

But the real issue is the `$html` variable, which might be several hundred thousand lines long.

My initial reaction was: I'll just read that string in chunks. There's [fread](https://www.php.net/fread) for files, but not for strings.

What's the safest way to read a string in chunks to avoid out of memory errors?

(I really want to avoid looping a string with `$html[0]`,  `$html[1]`, ... )

**Comment by pieterbeulque** [comment]
My first attempt would be to loop over the string with `strpos`:

```php
while ($newline = strpos($html, PHP_EOL) !== false) {
  $lines[] = substr($html, 0, $newline);
  $html = substr($html, $newline);
}
```

But I think that could be significantly slower.

**Comment by fntneves** [comment]
What about using stream resources? Write it to a temp file and then use stream functions.

**Comment by gopalkumar315** [comment]
Will increase memory size.

**Comment by jerodev** [comment]
Would it be possible to rewrite the class using resources instead of reading the file as a string?

**Comment by willemwollebrants** [comment]
I would use a stream in a generator:
```php
    protected function findRobotsMetaTagLine(string $html): ?string
    {
        function readLineFromStream(string $str)
        {
            $stream = fopen('php://memory', 'r+');
            fwrite($stream, $str);
            rewind($stream);

            while (($line = fgets($stream)) !== false) {
                yield($line);
            }
        }

        foreach (readLineFromStream($html) as $line) {
            if (strpos(strtolower(trim($line)), '<meta name="robots"') === 0) {
                return $line;
            }
        }

        return null;
    }
```

**Comment by mattiasgeniar** [comment]
@willemwollebrants damn that's clever code, hadn't thought of that yet!

**Comment by mattiasgeniar** [comment]
Decided to fix this in the [implementation of RobotsMeta](https://github.com/spatie/crawler/pull/281) instead of the actual class itself, will close for now.
