### ISSUE TITLE
Several user-agent for one Disallow directive does not work

### ISSUE THREAD

**Issue by nicoja** [spatie/robots-txt#28]
Hi,
for example : 

User-agent: UA1
User-agent: UA2
User-agent: UA3
Disallow: /

Only UA3 is disallowed, but UA1 and UA2 should also be disallowed.

**Comment by nicoja** [comment]
Cannot create PR, but in RobotsTxt.php this modification should do the job : 

`

    protected function getDisallowsPerUserAgent(string $content): array
    {
        $lines = explode(PHP_EOL, $content);

        $lines = array_filter($lines);

        $disallowsPerUserAgent = [];

        $currentUserAgents = [];

        foreach ($lines as $line) {
            if ($this->isCommentLine($line)) {
                continue;
            }

            if ($this->isUserAgentLine($line)) {
                $disallowsPerUserAgent[$this->parseUserAgent($line)] = [];

                $currentUserAgents[] = &$disallowsPerUserAgent[$this->parseUserAgent($line)];

                continue;
            }

            if (count($currentUserAgents) === 0) {
                continue;
            }

            $disallowUrl = $this->parseDisallow($line);

            foreach ($currentUserAgents as &$currentUserAgent) {
                $currentUserAgent[$disallowUrl] = $disallowUrl;
            }
            $currentUserAgents = [];
        }

        return $disallowsPerUserAgent;
    }

`

**Comment by freekmurze** [comment]
We'd accept a PR to fix this. Make sure to include tests.

**Comment by nicoja** [comment]
You right, I ll adjust and make the PR

**Comment by nicoja** [comment]
@freekmurze PR is done with tests, hope you ll merge.

**Comment by freekmurze** [comment]
Will be handled in #29
