### ISSUE TITLE
Not working properly with: x-robots-tag: none

### ISSUE THREAD

**Issue by nnerijuss** [spatie/robots-txt#30]
Not working properly with: `x-robots-tag: none`. 

This tag is equal to `noindex` and `nofollow`, but `->mayIndex()` and `->mayFollow()` returns `true`

**Comment by freekmurze** [comment]
Feel free to send a PR to fix this 👍

**Comment by nnerijuss** [comment]
@freekmurze can we expect merge any time soon ?

**Comment by freekmurze** [comment]
We'll handle this further in #30
