### ISSUE TITLE
Robots.txt fields should be case-insensitive

### ISSUE THREAD

**Issue by Redominus** [spatie/robots-txt#8]
According to [google robots.txt spec](https://developers.google.com/search/reference/robots_txt?hl=en), fields like: user-agent, disallow, etc are case insentitive.
`The <field> element is case-insensitive. The <value> element may be case-sensitive, depending on the <field> element.`

**Comment by freekmurze** [comment]
Feel free to send a PR for this.

**Comment by freekmurze** [comment]
We'll handle this further in #9
